WITH CTE AS(
    SELECT BOOK_ID,
        COUNT(RECORD_ID) AS BORROWED
        FROM BORROWING_RECORDS 
        WHERE RETURN_DATE IS NULL
        GROUP BY BOOK_ID
)

SELECT C.BOOK_ID AS book_id,L.TITLE as title,L.AUTHOR as author,L.GENRE as genre,L.PUBLICATION_YEAR as publication_year, C.BORROWED as current_borrowers
FROM CTE C JOIN library_books L ON C.BOOK_ID = L.BOOK_ID
AND C.BORROWED = L.TOTAL_COPIES
ORDER BY BORROWED DESC , L.TITLE
