WITH CTE AS (
    SELECT QUERY_NAME , COUNT(RATING) AS LESS_RATING FROM QUERIES WHERE RATING < 3 GROUP BY QUERY_NAME
)
SELECT Q.QUERY_NAME , ROUND(AVG(Q.RATING / Q.POSITION),2) AS QUALITY, IFNULL(ROUND(C.LESS_RATING / COUNT(*) * 100, 2), 0)
AS POOR_QUERY_PERCENTAGE FROM QUERIES Q LEFT JOIN CTE C ON Q.QUERY_NAME = C.QUERY_NAME
GROUP BY QUERY_NAME
