WITH CTE AS(
    SELECT 
        PRODUCT_ID,
        SUM(UNIT) AS SU
    FROM ORDERS WHERE MONTH(ORDER_DATE) = '02'
    AND YEAR(ORDER_DATE) = "2020"
    GROUP BY PRODUCT_ID
    HAVING SUM(UNIT)>=100
)
SELECT P.PRODUCT_NAME , C.SU AS UNIT FROM PRODUCTS P 
JOIN CTE C ON C.PRODUCT_ID = P.PRODUCT_ID