SELECT 
    P.PRODUCT_NAME,
    SUM(O.UNIT) AS UNIT
FROM PRODUCTS P JOIN ORDERS O 
    ON P.PRODUCT_ID = O.PRODUCT_ID 
    AND MONTH(O.ORDER_DATE)=2 AND YEAR(O.ORDER_DATE)=2020
GROUP BY PRODUCT_NAME
HAVING UNIT>=100