WITH CTE AS (
    SELECT 
        S.USER_ID, 
        COUNT(*) AS TOT
    FROM SIGNUPS S
    LEFT JOIN CONFIRMATIONS C 
        ON S.USER_ID = C.USER_ID
    GROUP BY S.USER_ID
),
CTE2 AS (
    SELECT 
        S.USER_ID,
        COUNT(*) AS CONFI
    FROM SIGNUPS S
    LEFT JOIN CONFIRMATIONS C  
        ON S.USER_ID = C.USER_ID
    WHERE C.ACTION = 'confirmed'
    GROUP BY S.USER_ID
)
SELECT 
    C.USER_ID, 
    ROUND(CAST(IFNULL(C1.CONFI,0) AS DECIMAL) / C.TOT, 2) AS CONFIRMATION_RATE
FROM CTE C
LEFT JOIN CTE2 C1 
    ON C.USER_ID = C1.USER_ID;
