WITH CTE AS (
    SELECT 
        ID,
        SALARY,
        DENSE_RANK() OVER(ORDER BY SALARY DESC) AS RNK
    FROM EMPLOYEE
)
SELECT IFNULL((
    SELECT SALARY FROM CTE WHERE RNK = 2 LIMIT 1
),NULL) AS SecondHighestSalary