SELECT 
    A1.MACHINE_ID,
    ROUND(AVG(B1.TIMESTAMP-A1.TIMESTAMP),3) AS PROCESSING_TIME
FROM ACTIVITY A1 JOIN ACTIVITY B1 
ON A1.MACHINE_ID = B1.MACHINE_ID AND A1.PROCESS_ID = B1.PROCESS_ID 
AND A1.ACTIVITY_TYPE = 'START' AND B1.ACTIVITY_TYPE = 'END'
GROUP BY A1.MACHINE_ID