WITH CTE AS(
    SELECT 
        U.NAME,
        U.USER_ID,
        COUNT(M.USER_ID) AS CNT
    FROM USERS U JOIN MOVIERATING M 
    ON U.USER_ID = M.USER_ID
    GROUP BY U.USER_ID,U.NAME
)
,RATING AS(
    SELECT 
        M.TITLE,
        M.MOVIE_ID,
        AVG(MO.RATING) AS AVERAGE
    FROM MOVIES M JOIN MOVIERATING MO 
    ON M.MOVIE_ID = MO.MOVIE_ID
    WHERE MONTH(CREATED_AT) = '02' AND YEAR(CREATED_AT) = '2020'
    GROUP BY M.TITLE,M.MOVIE_ID
)
(SELECT NAME AS RESULTS FROM CTE ORDER BY CNT DESC , NAME ASC LIMIT 1)

UNION ALL

(SELECT TITLE AS RESULS FROM RATING ORDER BY AVERAGE DESC , TITLE ASC LIMIT 1)
