WITH CTE AS (
    SELECT COUNT(*) AS CNT FROM USERS
)
SELECT R.CONTEST_ID,ROUND((COUNT(R.USER_ID)/C.CNT)*100,2) AS PERCENTAGE FROM REGISTER R , CTE C
GROUP BY R.CONTEST_ID 
ORDER BY PERCENTAGE DESC , R.CONTEST_ID 

