WITH CTE AS (
    SELECT REQUESTER_ID FROM REQUESTACCEPTED
    UNION ALL 
    SELECT ACCEPTER_ID FROM REQUESTACCEPTED
)
SELECT REQUESTER_ID AS ID , COUNT(REQUESTER_ID) AS NUM FROM CTE GROUP BY REQUESTER_ID 
ORDER BY NUM DESC
LIMIT 1
